/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./src/components/session/BottomBar.vue')['default']
    CountdownTimer: typeof import('./src/components/session/CountdownTimer.vue')['default']
    FloatingItem: typeof import('./src/components/FloatingItem.vue')['default']
    FormEditarPerfil: typeof import('./src/components/Forms/FormEditarPerfil.vue')['default']
    FormLogin: typeof import('./src/components/Forms/FormLogin.vue')['default']
    FormRegister: typeof import('./src/components/Forms/FormRegister.vue')['default']
    FormSessio: typeof import('./src/components/Forms/FormSessio.vue')['default']
    GameNotification: typeof import('./src/components/session/GameNotification.vue')['default']
    LevelProgressBar: typeof import('./src/components/session/LevelProgressBar.vue')['default']
    ListSessions: typeof import('./src/components/ListSessions.vue')['default']
    LoadingScreen: typeof import('./src/components/Ai/LoadingScreen.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NotificationCenter: typeof import('./src/components/session/NotificationCenter.vue')['default']
    PoseSkeleton: typeof import('./src/components/Ai/PoseSkeleton.vue')['default']
    ProgressInfo: typeof import('./src/components/session/ProgressInfo.vue')['default']
    ReadyCard: typeof import('./src/components/session/ReadyCard.vue')['default']
    RestScreen: typeof import('./src/components/session/RestScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionBottomBar: typeof import('./src/components/session/BottomBar.vue')['default']
    SessionEndScreen: typeof import('./src/components/session/SessionEndScreen.vue')['default']
    SessionExerciseInfo: typeof import('./src/components/session/SessionExerciseInfo.vue')['default']
    SessionScoreboard: typeof import('./src/components/session/SessionScoreboard.vue')['default']
  }
}
