const MESSAGE_TYPES = {
  SESSIONS_UPDATE: "SESSIONS_UPDATE",
  SESSION_UPDATE: "SESSION_UPDATE",
  UPDATE_SCORE: "UPDATE_SCORE",
  REGISTER_WEBSOCKET: "REGISTER_WEBSOCKET",
  REGISTER_USER: "REGISTER_USER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_USER: "LOGIN_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  CREATE_SESSION: "CREATE_SESSION",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  JOIN_SESSION: "JOIN_SESSION",
  JOIN_SUCCESS: "JOIN_SUCCESS",
  DELETE_SESSION: "DELETE_SESSION",
  LEAVE_SESSION: "LEAVE_SESSION",
  LEAVE_SUCCESS: "LEAVE_SUCCESS",
  ERROR: "ERROR",
  NEXT_EXERCISE: "NEXT_EXERCISE",
  INCREMENT_REPETITIONS: "INCREMENT_REPETITIONS",
};

export { MESSAGE_TYPES };
